---
integration:
  name: minitest
requires:
  - boa
includes:
  - test
mutation:
  operators: full
matcher:
  subjects:
    - Boa*
  ignore:
    - Boa#model                     # T.unsafe is removed, but is required by sorbet
    - Boa::Equality#eql?            # T.nilable is removed, but is required by sorbet
    - Boa::ModelMethods#properties  # T.nilable is removed, but is required by sorbet
    - Boa::Type#initialize          # T.nilable is removed, but is required by sorbet
    - Boa::Type.base_types          # T.let is removed, but is required by sorbet
    - Boa::Type::String#initialize  # T::Range[::Integer] is mutated to T::Range[Integer] which is wrong
    - Boa::Type::String#min_length  # T.must is removed, but is required by sorbet
