---
integration:
  name: minitest
requires:
  - boa
includes:
  - test
mutation:
  ignore_patterns:
    - send{receiver=const{name=T}}
    - send{receiver=send{receiver=const{name=T}}}
  operators: full
matcher:
  subjects:
    - Boa*
  ignore:
    - Boa::Type::Integer#initialize # Sorbet requires the default value for range
    - Boa::Type::String#initialize  # Sorbet requires the default value for length
