---
integration:
  name: minitest
requires:
  - boa
includes:
  - test
mutation:
  ignore_patterns:
    - send{receiver=const{name=T}}
    - send{receiver=send{receiver=const{name=T}}}
  operators: full
matcher:
  subjects:
    - Boa*
