inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-sorbet

AllCops:
  NewCops: enable
  EnabledByDefault: true
  Exclude:
    - vendor/**/*

Layout/ExtraSpacing:
  ForceEqualSignAlignment: true

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

Layout/HashAlignment:
  EnforcedColonStyle: table

Layout/IndentationWidth:
  Width: 2

Layout/LineLength:
  Max: 132

Layout/RedundantLineBreak:
  Enabled: false

Lint/ConstantResolution:
  Enabled: false

Metrics/MethodLength:
  Max: 10

Naming/BlockForwarding:
  EnforcedStyle: explicit

Sorbet/RedundantExtendTSig:
  Enabled: false

Sorbet/StrictSigil:
  Exclude:
    - sorbet/tapioca/require.rb

Sorbet/StrongSigil:
  Exclude:
    - sorbet/tapioca/require.rb

Style/AccessorGrouping:
  Enabled: false

Style/ArgumentsForwarding:
  UseAnonymousForwarding: false

Style/Attr:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/InlineComment:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  EnforcedStyle: require_parentheses
  Exclude:
    - Gemfile
  IgnoreMacros: false

Style/RequireOrder:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes
  Exclude:
    - sorbet/rbi/*.rbi
