inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake
  - rubocop-sorbet
  - rubocop-yard

AllCops:
  NewCops: enable
  EnabledByDefault: true
  Exclude:
    - sorbet/tapioca/require.rb
    - vendor/**/*

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/ExtraSpacing:
  ForceEqualSignAlignment: true

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

Layout/HashAlignment:
  EnforcedColonStyle: table

Layout/IndentationWidth:
  Width: 2

Layout/LineLength:
  Max: 132

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/RedundantLineBreak:
  Enabled: false

Lint/ConstantResolution:
  Enabled: false

Lint/UnreachableLoop:
  Exclude:
    - test/unit/boa/result_test.rb

Metrics/AbcSize:
  Exclude:
    - test/support/**/*.rb
    - test/unit/boa/util_test.rb

Metrics/BlockLength:
  Exclude:
    - test/**/*.rb

Metrics/MethodLength:
  Max: 10
  Exclude:
    - spec/doctest_helper.rb
    - test/support/**/*.rb
    - test/unit/boa/util_test.rb

Metrics/ModuleLength:
  Exclude:
    - test/support/**/*.rb

Naming/BlockForwarding:
  EnforcedStyle: explicit

Performance/ArraySemiInfiniteRangeSlice:
  Enabled: false

Performance/ChainArrayAllocation:
  Exclude:
    - test/unit/boa/result_test.rb

Performance/RedundantBlockCall:
  Enabled: false

Security/CompoundHash:
  Exclude:
    - lib/boa/instance_methods.rb

Sorbet/ForbidTStruct:
  Enabled: false

Sorbet/ForbidTUntyped:
  Exclude:
    - lib/boa/class_methods.rb
    - lib/boa/type.rb
    - test/support/property_generators.rb
    - test/support/type_behaviour.rb
    - test/unit/boa/result_test.rb

Sorbet/RedundantExtendTSig:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

Style/ArgumentsForwarding:
  UseAnonymousForwarding: false

Style/Attr:
  Enabled: false

Style/ConstantVisibility:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/ImplicitRuntimeError:
  Enabled: false

Style/InlineComment:
  Enabled: false

Style/InvertibleUnlessCondition:
  Enabled: false

Style/LambdaCall:
  EnforcedStyle: braces

Style/MethodCallWithArgsParentheses:
  AllowedMethods:
    - attr_reader
    - attr_writer
    - const
    - cover
    - describe
    - extend
    - include
    - include_context
    - include_examples
    - it
    - prop
    - protected
    - public_constant
    - require
    - require_relative
    - shared_context
    - shared_examples
  EnforcedStyle: require_parentheses
  Exclude:
    - .simplecov
    - Gemfile
  IgnoreMacros: false

Style/MixinUsage:
  Exclude:
    - spec/doctest_helper.rb

Style/ParallelAssignment:
  Enabled: false

Style/RequireOrder:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes
  Exclude:
    - sorbet/rbi/*.rbi

Style/TopLevelMethodDefinition:
  Exclude:
    - spec/doctest_helper.rb
