name: Boa Gem CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Fetch current branch
      uses: actions/checkout@v4

    - name: Cache Ruby Advisory Database
      uses: actions/cache@v3
      with:
        path: ~/.local/share/ruby-advisory-db
        key: ruby-advisory-db-${{ hashFiles('Gemfile.lock') }}
        restore-keys: ruby-advisory-db-

    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Check for vulnerabilities
      run: bundle exec bundler-audit check --update

    - name: Check Gemfile for up-to-date gems
      run: |
        bundle config unset deployment
        bundle outdated

    - name: Lint code
      run: bundle exec rubocop --fail-fast

    - name: Regenerate Gemfile.lock
      run: |
        # Upgrade rubygems and bundler to latest versions
        gem update --no-document --silent --system
        gem update bundler --no-document --silent

        # Regenerate Gemfile.lock
        rm -- Gemfile.lock
        bundle config set --local frozen false
        bundle lock --add-platform arm64-darwin-22
        bundle lock --add-platform x86_64-linux
        bundle --quiet

    - name: Check for unexpected file changes
      run: |
        set +o errexit

        # Check for unexpected file changes or deletions
        git diff --exit-code
        diff_exit_code=$?

        # Check for untracked files
        git ls-files --exclude-standard --others | grep .
        status_exit_code=$?

        set -o errexit

        test $diff_exit_code -eq 0 -a $status_exit_code -eq 1
