name: Boa Gem CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Fetch current branch
      uses: actions/checkout@v4

    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Check Gemfile for up-to-date gems
      run: |
        bundle config unset deployment
        bundle outdated

    - name: Check for unexpected file changes
      run: |
        set +o errexit

        # Check for unexpected file changes or deletions
        git diff --exit-code
        diff_exit_code=$?

        # Check for untracked files
        git ls-files --exclude-standard --others | grep .
        status_exit_code=$?

        set -o errexit

        test $diff_exit_code -eq 0 -a $status_exit_code -eq 1
