name: Boa Gem CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Fetch current branch
      uses: actions/checkout@v4

    - name: Fetch main branch
      if: github.ref != 'refs/heads/main'
      run: git fetch --depth 1 --quiet -- origin main

    - name: Cache Ruby Advisory Database
      uses: actions/cache@v4
      with:
        path: ~/.local/share/ruby-advisory-db
        key: ruby-advisory-db-${{ hashFiles('Gemfile.lock') }}
        restore-keys: ruby-advisory-db-

    - name: Cache sorbet files
      uses: actions/cache@v4
      with:
        path: |
          sorbet/rbi
          sorbet/tapioca
        key: sorbet-${{ hashFiles('Gemfile.lock', 'sorbet/config') }}
        restore-keys: sorbet-

    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Check for vulnerabilities
      run: bundle exec bundler-audit check --update

    - name: Lint code
      run: bundle exec rubocop --fail-fast

    - name: Build sorbet rbi files
      run: |
        bundle exec tapioca init
        rm -r -- bin

    - name: Check types
      run: bundle exec srb typecheck

    - name: Run unit tests
      run: bundle exec rake test

    - name: Run mutation tests
      run: bundle exec mutant run

    - name: Run docs tests
      run: bundle exec yard doctest

    - name: Check YARD doc coverage
      run: bundle exec yardstick -- lib

    - name: Generate YARD docs
      run: bundle exec yard

    - name: Regenerate RuboCop todo
      run: bundle exec rubocop --auto-gen-config --no-auto-gen-timestamp --no-exclude-limit

    - name: Check for unexpected file changes
      run: |
        set +o errexit

        # Check for unexpected file changes or deletions
        git diff --exit-code
        diff_exit_code=$?

        # Check for untracked files
        git ls-files --exclude-standard --others | grep .
        status_exit_code=$?

        set -o errexit

        test $diff_exit_code -eq 0 -a $status_exit_code -eq 1

    - name: Save YARD docs
      uses: actions/upload-artifact@v4
      with:
        name: yard-docs
        path: doc

    - name: Save Code Coverage
      uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: coverage
